version: "3"
services:
  app:
    build:
      context: .
    container_name: task-management-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=publicPassword
      - DB_DATABASE=task_management
      - JWT_SECRET=your_secret_key
    depends_on:
      - db
  db:
    image: mysql:5.7
    container_name: task-management-db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: publicPassword
      MYSQL_DATABASE: task_management
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: